utooland/utoo

packages/create-mako/templates/react/public/index.html
=> fix(create-mako): stylesheet don't work

e2e/fixtures/code-splitting.complex/expect.js
=> fix: e2e code-splitting.complex

crates/binding/src/lib.rs, crates/mako/src/config/config.rs, packages/mako/binding.d.ts
rename node_modules_regexes to internal
=> chore: rename node_modules_regexes to internal

crates/mako/src/plugins/emotion.rs
=> feat: ✨ disable emotion source map in prod

Cargo.lock, crates/mako/Cargo.toml
we don't need "node" just base enough
=> feat: ✨ change swc_core feature base_node to base 

crates/binding/src/js_hook.rs, crates/binding/src/js_plugin.rs, docs/config.md, docs/config.zh-CN.md, packages/mako/binding.d.ts
=> feat: add transformInclude plugin hook

crates/mako/src/config/mako.config.default.json, e2e/fixtures/config.inline_css/mako.config.json
Close https://github.com/umijs/mako/issues/1062
Ref: https://github.com/rust-cli/config-rs/issues/461
=> fix: inline css config deserialize

packages/mako/src/cli.ts
e.g.
```bash
$ npm run build:client
```
---
=> fix(mako): cli delay exit

crates/mako/src/visitors/virtual_css_modules.rs, examples/rsc/src/c.module.scss, examples/rsc/src/index.tsx
- 增加对module.scss 文件css module语法的处理，防止css module忽略这些文件
---
=> fix: mako已经支持了scss 但是没有支持module.scss文件

.github/workflows/bench.yml, .github/workflows/release.yml, crates/cli/src/bin/utoo-deps.rs, crates/cli/src/bin/utoo-rebuild.rs, crates/cli/src/helper/auto_update.rs, crates/cli/src/main.rs, package-lock.json, vendor/scripts/npm-binary.sh, vendor/scripts/npm-main.sh
> see https://github.com/umijs/mako/actions/runs/14028431328
* fix `--provenance` error
* add `set -e` to exit when error
=> fix: release flow

.github/workflows/release.yml, crates/cli/src/helper/auto_update.rs
* 🐞 fix autoupload not work
* 📦 `Upload Release Asset` in release workflow
=> feat: upload binary assets in release

crates/cli/src/main.rs
* auto update should follow `--registry`  config
=> fix: auto update

Cargo.lock, crates/cli/Cargo.toml, crates/cli/src/main.rs, crates/cli/src/util/config.rs, crates/core/src/config.rs, crates/core/src/lib.rs, crates/core/src/main.rs
> load `--registry` by utoo-core::config
* init utoo-core lib
* add `list` cmd for utoo-core
=> refact(cli): use utoo-core to load config

Cargo.lock, crates/cli/Cargo.toml, crates/cli/src/cmd/deps.rs, crates/cli/src/helper/package.rs, crates/cli/src/helper/ruborist.rs, crates/cli/src/main.rs, crates/cli/src/util/config.rs, crates/cli/src/util/mod.rs, crates/cli/src/util/node.rs, crates/cli/src/util/semver.rs, crates/core/src/config.rs, crates/core/src/lib.rs, crates/core/src/main.rs
1. Added `Display` Trait to print parent chain in verbose mode
2. Use `deno_semver` to replace `semver` to solve the fixed version matching problem
3. Added `validate_deps` fn to parsing exceptions in concurrent scenarios
=> fix: deps resolve

Cargo.lock, crates/cli/src/cmd/deps.rs, crates/cli/src/helper/package.rs, crates/cli/src/helper/ruborist.rs, crates/cli/src/main.rs, crates/cli/src/service/script.rs, crates/cli/src/util/config.rs
* support `--legacy-peer-deps` config for deps & install
* fix validate_deps warning for workspace node
=> feat: legacy peer deps

Cargo.lock, crates/cli/Cargo.toml, crates/cli/src/helper/ruborist.rs, crates/cli/src/util/node.rs
* use util#semver to match versions directly
=> refactor(cli): deno semver match

.cargo/config.toml, .github/workflows/bundler-release.yml, packages/bundler/package.json
* fix duplicated x64 binary publish
* support incremental build
=> fix: napi prepublish

packages/bundler/bin/cli.js
=> fix: shibang

crates/bundler-api/src/library.rs, crates/bundler-api/src/project.rs, crates/bundler-core/src/client/context.rs, crates/bundler-core/src/config.rs, crates/bundler-core/src/import_map.rs, crates/bundler-core/src/shared/webpack_rules/mod.rs, examples/with-antd/package.json, examples/with-antd/project_options.json, examples/with-antd/tsconfig.json, package-lock.json, package.json, packages/bundler/package.json, packages/bundler/src/index.ts, packages/bundler/src/types.ts
1. move the transpiled webpack loaders asset to .turbopack dir
2. sync some updates with next.js 15.3.0
=> fix(bundler): fix library dist

.github/workflows/release.yml, Cargo.lock, crates/cli/Cargo.toml, crates/cli/src/service/install.rs, crates/cli/src/util/registry.rs
1. Add network perf log for registry.rs
2. Optimize error logs to record current processing tasks when install deps
3. Compatible with  no name workspaces.
4. Add `utoo-core` for release
=> fix: deps npe

packages/bundler/npm/darwin-arm64/package.json, packages/bundler/npm/darwin-x64/package.json, packages/bundler/npm/linux-arm64-gnu/package.json, packages/bundler/npm/linux-arm64-musl/package.json, packages/bundler/npm/linux-x64-gnu/package.json, packages/bundler/npm/linux-x64-musl/package.json, packages/bundler/npm/win32-x64-msvc/package.json, packages/bundler/package.json, packages/bundler/src/index.ts, packages/bundler/src/util.ts
Close: https://github.com/umijs/mako/issues/1829
=> feat(bundler): emit bundling issues

crates/bundler-api/src/library.rs, crates/bundler-core/src/library/ecmascript/chunk.rs
* support `filename` config in `project_options.json`
=> feat: entry filename

crates/cli/src/util/cloner.rs
* ⚠️ Linux FICLONE doesn't support folder copying - need to implement folder traversal for cloning
=> fix: linux clonefile exception

.github/workflows/release.yml
=> chore: ubuntu 22.04

.github/workflows/ci.yml, .github/workflows/release.yml, crates/cli/src/util/cloner.rs
* 🐛 fix clonefile Linux build error
=> fix(cli): linux build

.github/workflows/ci.yml, .github/workflows/release.yml, crates/cli/Cargo.toml
* ⚙️ Update cli-release config to add APK related environment dependencies
=> chore: libssl

crates/bundler-api/src/library.rs, crates/bundler-api/src/project.rs, crates/bundler-cli/src/main.rs, crates/bundler-core/src/client/context.rs, crates/bundler-core/src/config.rs, crates/bundler-core/src/import_map.rs, crates/bundler-core/src/library/chunking_context.rs, crates/bundler-core/src/library/contexts.rs, crates/bundler-core/src/library/ecmascript/content.rs, crates/bundler-core/src/mode.rs, crates/bundler-napi/src/bundler_api/project.rs, crates/bundler-napi/src/bundler_api/utils.rs, examples/with-antd/project_options.json, examples/with-less/project_options.json, examples/with-sass/project_options.json, examples/with-style-loader/project_options.json, packages/bundler/src/binding.d.ts, packages/bundler/src/index.ts, packages/bundler/src/project.ts, packages/bundler/src/types.ts
Close https://github.com/umijs/mako/issues/1837
=> refactor(bundler): align some configs with webpack

Cargo.lock, crates/cli/Cargo.toml, crates/cli/src/util/cloner.rs
* disable `default-features` for `native-lts`
=> chore: linux libssl

crates/cli/src/util/cloner.rs
=> fix: linux build

.github/workflows/release.yml, crates/cli/Cargo.toml
* 🐳 Specify Docker image to avoid 'GLIBC_2.33' error
=> chore: docker build

.github/workflows/release.yml
🔧 Resolved GitHub Actions artifact upload problems in container
=> chore: upload release artifact

crates/bundler-api/src/library.rs, crates/bundler-api/src/project.rs, crates/bundler-core/src/config.rs, crates/bundler-core/src/library/chunking_context.rs, crates/bundler-core/src/library/contexts.rs, crates/bundler-core/src/library/ecmascript/content.rs, crates/bundler-core/src/library/mod.rs, crates/bundler-core/src/library/runtime/asset_context.rs, crates/bundler-core/src/library/runtime/embed_js.rs, crates/bundler-core/src/library/runtime/mod.rs, crates/bundler-core/src/library/runtime/runtime_code.rs, examples/with-library/.gitignore, examples/with-library/genHtml.js, examples/with-library/package.json, examples/with-library/project_options.json, examples/with-library/src/index.ts, packages/bundler/src/binding.d.ts
Support:
library.name: https://webpack.js.org/configuration/output/#outputlibraryname
library.export: https://webpack.js.org/configuration/output/#outputlibraryexport
=> feat(bundler): support umd project (PART3)

Cargo.lock, Cargo.toml, crates/bundler-api/Cargo.toml, crates/bundler-api/src/library.rs, crates/bundler-api/src/project.rs, crates/bundler-core/src/library/chunking_context.rs, examples/with-library/project_options.json
Partially support filename template "[name]"
See: https://webpack.js.org/configuration/output/#template-strings
=> feat(bundler): support filename template with [name]

.github/workflows/release.yml, Cargo.lock, crates/cli/Cargo.toml, crates/cli/src/bin/utoo-update.rs, crates/cli/src/cmd/mod.rs, crates/cli/src/cmd/update.rs, crates/cli/src/constants.rs, crates/cli/src/helper/mod.rs, crates/cli/src/helper/ruborist.rs, crates/cli/src/helper/workspace.rs, crates/cli/src/main.rs, crates/cli/src/service/mod.rs, crates/cli/src/service/update.rs
* 🧹 Add utoo-update feature: Remove node_modules & package-lock.json, reinstall dependencies
* 📦 Add standalone `utoo-update` binary entry and release flow
=> feat: utoo-update

crates/cli/src/cmd/mod.rs, crates/cli/src/cmd/run.rs, crates/cli/src/main.rs, crates/cli/src/service/script.rs
* 🎯 Supports executing scripts defined in package.json
* ♻️ Direct child process spawning without npm
=> feat: add utoo run command with full stdio support

crates/bundler-api/src/operation.rs, crates/bundler-napi/src/bundler_api/endpoint.rs, crates/bundler-napi/src/bundler_api/project.rs, crates/bundler-napi/src/bundler_api/utils.rs, packages/bundler/src/binding.d.ts, packages/bundler/src/binding.js, packages/bundler/src/index.ts, packages/bundler/src/project.ts, packages/bundler/src/util.ts
Sync updates with turbopack build.
=> feat(bundler): sync updates with next.js

crates/mako/src/generate.rs
=> fix: dev支持inline-source-map

crates/bundler-cli/src/main.rs, crates/bundler-core/src/tracing_presets.rs, crates/bundler-napi/src/bundler_api/project.rs, crates/bundler-napi/src/bundler_api/utils.rs, crates/bundler-napi/src/util.rs, packages/bundler/src/index.ts
Refactor the bundler tracing log.
=> feat(bundler): update bundler tracing log

.github/workflows/release.yml, Cargo.lock, crates/core/Cargo.toml, crates/core/src/config.rs, crates/core/src/main.rs, crates/core/src/service/cmd.rs, crates/core/src/service/mod.rs, vendor/scripts/npm-utoo.sh, vendor/templates/postinstall.utoo.sh.template, vendor/templates/utoo.package.json.template
* 🤖 Added `ut` bin name to `utoo-core` to support automatic command registration
* 📖 Updated `ut` help document output to automatically fallback commands to utoo
* 🔭 Modified the release flow and released the `utoo` main package
=> feat: utoo main pkg vendor & release flow

vendor/templates/utoo.package.json.template
=> fix: utoo vendor

vendor/templates/postinstall.sh.template
* 🐞 fix: nested postinstall binary replacement
=> fix: binary replace

README.md
=> Chore logo

Cargo.lock, Cargo.toml, packages/bundler/src/binding.d.ts
=> feat(bundler): update next.js to 15.3.2

README.md, crates/bundler-cli/src/lib.rs, crates/bundler-cli/src/main.rs
=> fix(bundler): fix bundler-cli

README.md
=> chore: svg

Cargo.lock, crates/bundler-api/Cargo.toml, crates/bundler-api/src/endpoints.rs, crates/bundler-api/src/entrypoints.rs, crates/bundler-api/src/hmr.rs, crates/bundler-api/src/issues.rs, crates/bundler-api/src/lib.rs, crates/bundler-api/src/project.rs, crates/bundler-api/src/source_map.rs, crates/bundler-api/src/tasks.rs, crates/bundler-api/src/utils.rs, crates/bundler-cli/src/lib.rs, crates/bundler-napi/Cargo.toml, crates/bundler-napi/src/bundler_api/endpoint.rs, crates/bundler-napi/src/bundler_api/project.rs, crates/bundler-napi/src/bundler_api/utils.rs
=> refactor(bundler): move shared codes into bundler-api

crates/cli/src/helper/lock.rs, crates/cli/src/service/install.rs, crates/cli/src/util/cloner.rs
* 📌 add `_hasInstallScript` flag for linux in global_store
* 🐧 linux `clone` operation auto fallback
=> feat: hardlink for linux fallback

.cargo/config.toml, .github/workflows/ci.yml, crates/cli/benches/deps_benchmark.rs, crates/cli/src/bin/utoo-install.rs, crates/cli/src/cmd/run.rs, crates/cli/src/helper/auto_update.rs, crates/cli/src/helper/compatibility.rs, crates/cli/src/helper/ruborist.rs, crates/cli/src/helper/workspace.rs, crates/cli/src/service/install.rs, crates/cli/src/util/cache.rs, crates/cli/src/util/downloader.rs, crates/core/src/main.rs, crates/core/src/service/cmd.rs
- enable `cargo clippy` check at ci branch
- run `cargo clippy` at my local to check  the code and follow the clippy suggestion to update code
=> chore(ci): enable clippy

crates/cli/src/helper/compatibility.rs, crates/cli/src/util/cloner.rs
* 🐞 fix linux x64 arch compatible 
* ♻️ clean hardlink log
=> fix: x64 arch

.github/workflows/ci.yml
follow up: https://github.com/umijs/mako/pull/1896#issuecomment-2884146501
=> chore: update clippy ci

packages/bundler/src/index.ts, packages/bundler/src/xcodeProfile.ts
=> perf(turbopack): add xcode profiling support for napi package

packages/mako/src/index.ts
=> fix: less resolve alias

packages/mako/src/runLoaders/parallelLoader.ts
=> fix: panic on docker linux

README.md
=> doc: add openomy

Cargo.lock, examples/with-less/package.json, examples/with-less/src/index.less, examples/with-sass/package.json, examples/with-sass/project_options.json, examples/with-sass/src/index.sass, package-lock.json
=> chore(bundler): improve examples

Cargo.lock
=> chore(bundler): update deps

crates/bundler-core/src/shared/webpack_rules/mod.rs
Close https://github.com/umijs/mako/issues/1889
=> perf(bundler): not compile loader-runner

.gitignore, Cargo.lock, Cargo.toml, crates/bundler-api/Cargo.toml, crates/bundler-core/Cargo.toml
=> chore: add xcode profiling comments

Cargo.lock, crates/bundler-cli/src/main.rs, examples/multiple-entries-heavy/.gitignore
=> chore(bundler): update binary tracing log

crates/cli/src/helper/lock.rs
=> fix: is_pkg_lock_outdated not work

Cargo.lock, Cargo.toml, crates/pack-core/Cargo.toml, crates/pack-core/src/library/chunking_context.rs, crates/pack-core/src/library/ecmascript/chunk.rs, examples/with-less/project_options.json, examples/with-sass/project_options.json, packages/pack/package.json
=> chore: faster local rustc

crates/pack-core/src/client/context.rs, crates/pack-core/src/library/contexts.rs
=> perf(pack): disable chunk filename template in dev mode

crates/pack-api/src/app.rs
Should not modify the entry request with `name` query, this will break the hmr subscription.
=> fix(pack-cli): hmr entry ident

crates/cli/src/helper/package.rs, crates/cli/src/helper/ruborist.rs, crates/cli/src/util/node.rs
* Added `parse_package_spec` to handle parsing and validation of package specifications.
=> fix: overrides rule parse

crates/pack-cli/src/main.rs, crates/pack-napi/src/pack_api/project.rs, crates/pack-napi/src/util.rs, package-lock.json, packages/pack-cli/package.json, packages/pack/package.json, packages/pack/src/build.ts, packages/pack/src/types.ts
- 避免 node 多次调用 napi build 出现 tracing 调用 panic(多线程处初始化)
- 调整一下 `packages/pack` 的本地构建产物，输出 esm & cjs
=> refactor: add tracing init protect && adjust napi pack script

crates/pack-napi/src/pack_api/project.rs
follow up: https://github.com/umijs/mako/pull/1967
=> fix: avoid tracing subscriber init more times

crates/pack-api/src/library.rs, crates/pack-core/src/config.rs, crates/pack-core/src/library/chunking_context.rs, crates/pack-core/src/library/contexts.rs, crates/pack-core/src/library/runtime/runtime_code.rs, crates/pack-schema/src/lib.rs, examples/with-library/package.json, examples/with-library/project_options.json, examples/with-library/src/comp2.tsx, packages/pack/config_schema.json, packages/pack/src/types.ts
library 支持可选值，参考 webpack 的配置说明: https://webpack.js.org/configuration/output/#type-umd
行为上也和 webpack 对齐: https://github.com/webpack/webpack/blob/main/lib/library/UmdLibraryPlugin.js#L335
`utoo-pack` 不设置 `library.name` 产物参考:
closes: #1964
=> feat(pack): library.name support optional

.github/workflows/pack-release.yml
=> feat: @utoo/pack-cli release

examples/webpack-compat/.gitignore, examples/webpack-compat/pack.ts, examples/webpack-compat/package.json, examples/webpack-compat/src/index.js, examples/webpack-compat/src/inline.html, examples/webpack-compat/tsconfig.json, examples/with-antd/package.json, package-lock.json, package.json, packages/pack-cli/package.json, packages/pack/package.json, packages/pack/src/build.ts, packages/pack/src/dev.ts, packages/pack/src/hmr.ts, packages/pack/src/index.ts, packages/pack/src/project.ts, packages/pack/src/types.ts, packages/pack/src/webpackCompat.ts
=> feat(pack): add webpack compat layer

packages/pack/data/features-list.json, packages/pack/data/features-list.md, packages/pack/package.json, packages/pack/scripts/generate-feature-list.js
=> chore: add script to generate utoopack features list

.github/workflows/ci.yml, .github/workflows/pack-release.yml, .gitmodules, Cargo.lock, Cargo.toml, crates/pack-core/src/library/chunking_context.rs
=> refactor: next.js submodule

.gitmodules
=> chore: enable git submodule shallow clone

Cargo.lock, Cargo.toml, crates/cli/Cargo.toml, crates/pack-cli/Cargo.toml, crates/pack-core/Cargo.toml, crates/pack-napi/Cargo.toml, crates/pack-schema/Cargo.toml
To reduce the binary size of utoo-pack.
=> chore(deps): remove unused deps with cargo-shear

.github/workflows/ci.yml, .github/workflows/pack-release.yml, .gitmodules
=> chore: update next.js submodule url

packages/pack/src/webpackCompat.ts
=> fix(pack): compat entry value array with single item

crates/pack-core/src/import_map.rs, packages/pack/src/webpackCompat.ts
=> fix(pack): disable shared import map now

crates/cli/src/bin/utoo-install.rs, crates/cli/src/cmd/install.rs, crates/cli/src/helper/lock.rs, crates/cli/src/main.rs
* 🔄 Added aliases for `save_dev` and `save_optional` to follow npm cli.
* 📦 `install / uninstall` now supports multiple dependencies.
=> feat(pm): save_type alias

.github/workflows/release.yml
* add SSH private keys for submodule repositories
=> chore: update pk

.github/workflows/bench.yml, .github/workflows/ci.yml, .github/workflows/release.yml, .vscode/setting.json, rust-toolchain.toml
=> chore: update next.js

.github/workflows/ci.yml
对 crates 做检查跑下 clippy 和 check 就好:
这里串行跑一次 build 会耗时很久，看上去 cargo 缓存也没有复用，等后面这里直接换成跑测试: https://github.com/umijs/mako/pull/2048
=> perf(ci): combine check and lint && remove build

Cargo.lock, crates/cli/Cargo.toml, crates/cli/src/cmd/clean.rs, crates/cli/src/helper/lock.rs, crates/cli/src/main.rs, crates/cli/src/service/binary.rs, crates/cli/src/util/cache.rs, crates/cli/src/util/cloner.rs, crates/cli/src/util/downloader.rs, crates/cli/src/util/registry.rs
* 🗑️ Removed default umask 000 – now handles chmod permissions exclusively in try_pack
* 🧹 Fixed clean not taking effect
* 🔒 Added idempotent lock for downloads to prevent race conditions
=> fix: concurrent tgz download pollution

crates/cli/src/cmd/install.rs, crates/cli/src/helper/ruborist.rs, crates/cli/src/main.rs, crates/cli/src/service/install.rs, crates/cli/src/service/package.rs, crates/cli/src/util/logger.rs
1. 🧹 **Clean up existing logs** – Disabled `log_info` by default
2. ✂️ **Simplify progress bar** – Reduced visual noise
3. ⏱️ **Auto time tracking** – Added `log_time_end` by default
=> feat(pm): log summary

biome.json
A tiny update follow up: https://github.com/umijs/mako/pull/2058/files#r2214743241
=> chore: update biome schema config

crates/pack-core/js/src/hmr/websocket.ts, package-lock.json, packages/pack/package.json, packages/pack/src/hmr.ts
A small patch follows: https://github.com/umijs/mako/pull/2069#discussion_r2224161375
=> chore: optimize code of runtime code websocket.ts

crates/cli/src/service/script.rs
1. 🤖 Automatically install `node-gyp` globally when detected in dependencies
=> feat(pm): node-gyp

crates/cli/src/service/workspace.rs, crates/cli/src/util/config.rs, crates/cli/src/util/downloader.rs, crates/cli/src/util/json.rs, crates/cli/src/util/node.rs, crates/cli/src/util/registry.rs
* ✅ Add support for `workspace:*` dependency declarations
* 🔗 Add `resolutions` protocol support
* 🛠 Fix dependency ordering issue for workspace-only packages
* ♻️ Add `UTOO_REGISTRY` env
=> fix: workspaces protocol

.github/workflows/release.yml, crates/pack-core/src/util.rs
* 🚚 fix binary release flow config
* 🧹 fix MAIN_SEPARATOR_STR lint
=> fix(pm): binary release

crates/pack-tests/tests/snapshot/externals/basic/output/__3d790e66.js
upgrade next.js to lastest
Update snapshot
=> chore: upgrade next.js to lastest

Cargo.toml
=> chore: update instruments guide

.cargo/config.toml, Cargo.lock, Cargo.toml, crates/pack-api/Cargo.toml, crates/pack-api/src/project.rs, crates/pack-cli/Cargo.toml, crates/pack-core/Cargo.toml, crates/pack-core/src/tracing_presets.rs, crates/pack-napi/Cargo.toml, crates/pack-napi/src/pack_api/project.rs, examples/react/.gitignore
=> feat: add wasm compatiable features

Cargo.lock, Cargo.toml, crates/opfs-project/Cargo.toml, crates/opfs-project/src/fuse.rs, crates/opfs-project/src/lib.rs, crates/opfs-project/src/mod.rs, crates/opfs-project/src/model/mod.rs, crates/opfs-project/src/model/package_lock.rs, crates/opfs-project/src/package_manager.rs, crates/opfs-project/src/util.rs, crates/utoo-wasm/Cargo.toml, crates/utoo-wasm/src/lib.rs, examples/wasm-hello/index.html, examples/wasm-hello/package.json, examples/wasm-hello/worker.js, package.json
* 📦 Added cli-shared for common logic
* 🔧 Created opfs-project with:
+ `install_deps` functionality
+ `read` operations
+ `read_dir` capabilities
* ⚡ File operations powerd by `tokio-fs-ext`
* 📂 cwd configuration & resolution
* 🎮 Added playground examples `wasm-hello`
```bash
$ ut build --workspace examples/wasm-hello
$ ut serve --workspace examples/wasm-hello
```
🔜 Upcoming PR will handle TODOs:
* 🔗 Nested node_modules symlinking
* 🧹 File deletion & cleanup operations
=> feat(wasm): init wasm

examples/utooweb-demo/src/OpfsProject.tsx
* 🐞 prevent re-renders when expanding nodes
=> fix(wasm): demo display

crates/utoo-wasm/Cargo.toml, packages/utoo-web/package.json
Fix probleam of https://github.com/wasm-bindgen/wasm-bindgen/issues/3451
=> wasm: utoo-wasm dev

Cargo.lock, crates/pack-core/src/import_map.rs
=> chore: update utoo-wasm & turbopack-node

examples/utooweb-demo/src/OpfsProject.tsx, examples/utooweb-demo/src/worker.ts, examples/utooweb-demo/tsconfig.json
Refactor with Copilot, amazing !
=> chore(wasm): update utooweb demo

.cargo/config.toml, .github/workflows/utooweb-release.yml, Cargo.lock, Cargo.toml, crates/pack-api/Cargo.toml, crates/pack-core/Cargo.toml, crates/utoo-wasm/Cargo.toml, examples/utooweb-demo/package.json, packages/utoo-web/.gitignore, packages/utoo-web/package.json
With `wasm-pack`, we can't keep the `DWARF` debug info, and can not parse large `wasm` file. Out  `utoo-wasm` dev compiled size is greater than `1GB`
Directly call `wam-bindgen`
=> feat(wasm): remove wasm-pack

crates/utoo-wasm/Cargo.toml, crates/utoo-wasm/build.rs, crates/utoo-wasm/src/lib.rs, crates/utoo-wasm/src/project.rs, packages/utoo-web/package.json
* 🔧 Added `utoo-pack` feature.
=> chore(wasm): update utoo-pack as a feature

examples/with-less/project_options.json, examples/with-less/src/index.less, examples/with-less/src/less-with-js-function.less, packages/pack/src/build.ts, packages/pack/src/index.ts
- 类型导出
- less example 加个 javascript enabled 的 case.
No test case.
=> chore: export types for utoopack

examples/define/package.json, examples/externals/package.json, examples/multi-entries-heavy/package.json, examples/react/package.json, examples/react/src/index.tsx, examples/react/src/typea.ts, examples/resolve/package.json, examples/split-chunks/package.json, examples/with-antd/package.json, examples/with-less/package.json, examples/with-less/project_options.json, examples/with-less/src/index.ts, examples/with-less/src/less-with-global.module.less, examples/with-library/package.json, examples/with-sass/package.json, examples/with-style-loader/package.json, examples/with-tailwind/package.json, package-lock.json, packages/pack-cli/src/commands/build.ts, packages/pack-cli/src/commands/dev.ts, packages/pack/package.json, packages/pack/src/build.ts, packages/pack/src/find-root.ts, packages/pack/src/index.ts
参考 next.js 的处理逻辑: https://nextjs.org/docs/app/api-reference/config/next-config-js/turbopack#root-directory
对 rootPath 加一层 fallback 的寻找逻辑，如果用户没用传这个参数的话。
No need test.
=> feat(pack): add findRoot method to fallback rootPath

crates/utoo-wasm/src/pack.rs, crates/utoo-wasm/src/project.rs, crates/utoo-wasm/src/tokio_runtime.rs, examples/utooweb-demo/src/OpfsProject.tsx, examples/utooweb-demo/src/tokio_worker.ts, examples/utooweb-demo/src/worker_thread.ts, examples/utooweb-demo/webpack.config.js, packages/utoo-web/src/index.ts, packages/utoo-web/src/type.ts, packages/utoo-web/src/worker.ts, packages/utoo-web/src/worker_thread.ts
=> feat(wasm): expose threadUrl

Cargo.toml, packages/utoo-web/package.json
=> chore: reduce wasm size

.github/PULL_REQUEST_TEMPLATE.md, .gitmodules, Cargo.toml, README.md, crates/core/src/service/cmd.rs, crates/pack-core/src/util.rs, crates/pack-napi/src/util.rs, examples/with-antd/package.json, examples/with-less/package.json, examples/with-library/package.json, examples/with-sass/package.json, examples/with-style-loader/package.json, package.json, packages/pack/docs/features-list.json, packages/pack/docs/features-list.md, packages/pack/package.json, vendor/templates/binary.package.json.template, vendor/templates/entry.package.json.template, vendor/templates/utoo.package.json.template
cherry-pick: https://github.com/utooland/utoo/pull/2152
=> chore: update umijs/mako to utooland/utoo

.github/PULL_REQUEST_TEMPLATE.md, .gitmodules, Cargo.toml, README.md, crates/core/src/service/cmd.rs, crates/pack-core/src/util.rs, crates/pack-napi/src/util.rs, examples/with-antd/package.json, examples/with-less/package.json, examples/with-library/package.json, examples/with-sass/package.json, examples/with-style-loader/package.json, package.json, packages/pack/docs/features-list.json, packages/pack/docs/features-list.md, packages/pack/package.json, packages/utoo-web/package.json, vendor/templates/binary.package.json.template, vendor/templates/entry.package.json.template, vendor/templates/utoo.package.json.template
- submodule branch 配置
- 仓库里的路径写法
=> chore: update `umijs/mako` to `utooland/utoo`

examples/utooweb-demo/index.html, examples/utooweb-demo/src/Project.tsx, examples/utooweb-demo/src/components/Editor.tsx, examples/utooweb-demo/src/components/FileTree.tsx, examples/utooweb-demo/src/components/Preview.tsx, examples/utooweb-demo/src/hooks/useBuild.ts, examples/utooweb-demo/src/hooks/useFileContent.ts, examples/utooweb-demo/src/hooks/useFileTree.ts, examples/utooweb-demo/src/hooks/useUtooProject.ts, examples/utooweb-demo/src/services/utooService.ts, examples/utooweb-demo/src/types/index.ts, examples/utooweb-demo/src/utils/htmlGenerator.ts, packages/utoo-web/src/index.ts, packages/utoo-web/src/serviceWorker.ts, packages/utoo-web/src/threadWorker.ts, packages/utoo-web/src/type.ts, packages/utoo-web/src/worker.ts
=> feat(wasm): resctrict serviceWorker scope

Cargo.lock, crates/utoo-wasm/Cargo.toml
=> chore: version bump

examples/utooweb-demo/src/Project.tsx, examples/utooweb-demo/src/components/Editor.tsx, examples/utooweb-demo/src/components/FileTree.tsx, examples/utooweb-demo/src/components/Panel.tsx, examples/utooweb-demo/src/components/Preview.tsx, examples/utooweb-demo/src/hooks/useFileTree.ts
=> chore: update utooweb-demo with viber coding

examples/utooweb-demo/src/demoFiles.ts, examples/utooweb-demo/webpack.config.js
- 加个 sass-demo
- 调整下 service-worker 的构建配置避免产物 syntax error
=> chore: add sass demo for utooweb-demo

crates/utoo-wasm/src/lib.rs
=> perf(wasm): avoid too many console.log

.github/workflows/pack-release.yml
ref: 
- https://github.com/utooland/utoo/pull/1980
- https://github.com/utooland/utoo/pull/2176/files
=> fix(ci): restore pack release musl ci RUSTFLAGS inject

crates/utoo-wasm/src/project.rs
propagate the build error detail to js.
=> feat(wasm): pretty build error

crates/pack-core/src/client/context.rs, examples/utooweb-demo/src/demoFiles.ts, packages/pack/docs/features-list.json, packages/pack/docs/features-list.md
=> fix(wasm): disable postcss temporarily

Cargo.lock, crates/pack-api/src/tasks.rs, crates/pack-core/src/util.rs, crates/pack-tests/tests/snapshot.rs
- 主要是把 RuleQuery 的改动同步进来了
- turbo_tasks 有一些 api 调整
测试更新了
=> chore: upgrade next.js

Cargo.lock, crates/utoo-wasm/Cargo.toml
=> chore(wasm): bump version

Cargo.lock, crates/pm/Cargo.toml, crates/pm/src/helper/auto_update.rs, crates/pm/src/helper/lock.rs, crates/pm/src/main.rs, crates/pm/src/service/binary.rs, crates/pm/src/service/http_client.rs, crates/pm/src/service/install.rs, crates/pm/src/util/config.rs, crates/pm/src/util/downloader.rs
* 🏄🏻 Download process is now stream-based
* 📦 Batch write downloaded files
=> refactor(pm): unzip op
