utooland/utoo

- crates/mako/src/build/transform.rs
- crates/mako/src/config/config.rs
- docs/config.md
- e2e/fixtures/javascript.transform.emit_decorator_metadata/expect.js
- e2e/fixtures/javascript.transform.emit_decorator_metadata/mako.config.json
- e2e/fixtures/javascript.transform.emit_decorator_metadata/src/index.ts
Close #1173
用例来自 https://github.com/leonardfactory/babel-plugin-transform-typescript-metadata/blob/master/test/__fixtures__/generics/code.js
参考：
https://www.typescriptlang.org/docs/handbook/decorators.html#metadata
https://github.com/leonardfactory/babel-plugin-transform-typescript-metadata
https://babeljs.io/docs/babel-plugin-transform-typescript#typescript-compiler-options
> feat: add emitDecoratorMetadata config

- crates/mako/src/cli.rs
after this,  i will never bother with miss-spelling
```bash
cargo mako  . --mode dev
cargo mako  . --mode prod
cargo mako  . --mode p
```
> feat: ✨ support mako cli using abbreviated mode value, like "prod"

- crates/mako/src/dev/watch.rs
This reverts commit 3a74d28a0eeb6c72f0c9773d91817ab78ecff701.
> Revert "fix: watch files change of module_graph in node_modules (#1385)"

- Cargo.toml
The default lto strategy ("fat") is slow, and with debug: true, it may cause OOM.
> chore: use lto: thin in release build

- crates/mako/src/plugins/duplicate_package_checker.rs
Before.
```
Building with mako for production...
● Mako ▨▨▨▨▨▨▨▨▨▨▨▨▨▨▨▨▨▨▨▨▨▨▨▨▨ (28%) transform_js transform_js                                                                thread 'Mako thread 10' panicked at crates/mako/src/plugins/duplicate_package_checker.rs:102:66:
called `Option::unwrap()` on a `None` value
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Rayon: detected unexpected panic; aborting
[1]    53972 abort      OKAM=  build
```
How to reproduce? 
```
umi g page index
umi config set mako {}
umi build
```
> fix: duplicate_package_checker panic when no package.json is supplied

- crates/binding/src/js_hook.rs
- crates/binding/src/js_plugin.rs
- docs/config.md
- docs/config.zh-CN.md
- e2e/fixtures/plugins/plugins.config.js
- packages/mako/binding.d.ts
> feat: add loadInclude plugin hook

- .github/ISSUE_TEMPLATE/bug_report.yml
- .github/ISSUE_TEMPLATE/config.yml
- .github/ISSUE_TEMPLATE/feature_request.yml
- .github/PULL_REQUEST_TEMPLATE.md
> chore: add issue and pull request templates for better contribution guidelines

- CONTRIBUTING.md
- package.json
- scripts/check-ecosystem-usages.ts
check ant-design with dumi and others later on. should be run after mako is released.
---
> chore: add check-ecosystem-usages script

- crates/mako/src/config.rs
- crates/mako/src/module_graph.rs
- e2e/fixtures/css.css-merge-multi-entries/expect.js
- e2e/fixtures/css.css-merge-multi-entries/mako.config.json
- e2e/fixtures/css.css-merge-multi-entries/src/a.css
- e2e/fixtures/css.css-merge-multi-entries/src/a.ts
- e2e/fixtures/css.css-merge-multi-entries/src/b.css
- e2e/fixtures/css.css-merge-multi-entries/src/b.ts
- e2e/fixtures/css.css-merge-multi-entries/src/c.css
- e2e/fixtures/css.css-merge-multi-entries/src/c.ts
- e2e/fixtures/css.css-merge-multi-entries/src/common_1.css
- e2e/fixtures/css.css-merge-multi-entries/src/common_2.css
- e2e/fixtures/css.css-merge-multi-entries/src/common_3.css
The entry modules' order should be stable, or else, the css order in common chunks will be unstable.
> fix: chunk groups' order when building mpa

- crates/binding/src/js_plugin.rs
- crates/binding/src/lib.rs
The js land should not hold a strong reference of PluginContext, or else, it will prevent Drop::drop of PluginHook, and the main thread will hang forever.
> fix: plugin context gc

- .github/workflows/bench.yml
- .github/workflows/ci.yml
- crates/cli/src/helper/auto_update.rs
- crates/cli/src/main.rs
- crates/cli/src/util/config.rs
- crates/cli/src/util/mod.rs
- crates/cli/src/util/registry.rs
* Added `--registry` global args to support custom registry configuration for dependency resolution and installation services.
* Due to reliance on `semver` version resolution, currently only support cnpmcore registry.
* Use `https://registry.npmmirror.com`  by default.
> feat: registry args

- Cargo.lock
- Cargo.toml
- crates/core/Cargo.toml
- crates/core/src/config.rs
- crates/core/src/error.rs
- crates/core/src/main.rs
**Changes:**  
1. Refactor `utoo` to focus solely on **configuration management**, with a default command flow.  
2. New `config` capabilities:  
- `utoo config set install.cmd utoo-install`  
- `utoo config set common.registry --global https://registry.npmmirror.com`  
3. `Next PR` Split subcommands (install/deps/clean/rebuild) into **standalone packages** (`utoo-*`), allowing:  
- Independent installation/usage  
- Custom implementations via replacement  
4. Enforce naming convention: future subcommands must follow `utoo-xxx` format and be independently distributable.  
**Impact:**  
- Cleaner core (`utoo`), extensible architecture  
- Users can opt-in to specific functionalities  
- Simplified maintenance and custom workflows
> feat: init utoo-core

- CHANGELOG_zh-CN.md
- crates/binding/src/js_plugin.rs
- e2e/fixtures/javascript.typescript/src/ts-advanced.ts
- e2e/fixtures/module-federation.producer/expect.js
Simplify before_rebuild hook logic.
> refactor: before_rebuild hook

- crates/cli/src/service/package.rs
- crates/cli/src/util/node.rs
- crates/cli/src/util/registry.rs
1. Follow `npm`. If a dependency declares both deps and optionalDeps, only keep optionalDeps.
2. Temporarily disable the scripts cache.
> fix: optional deps

- crates/cli/src/helper/ruborist.rs
* use `add_dependency_edge` to process edges
* ignore `workspace` when get_dup_nodes
> fix: legacy peer deps

- packages/mako/src/plugins/sass/index.ts
- packages/mako/src/plugins/sass/render.ts
- packages/mako/src/runLoaders/index.ts
disable parallel sassLoader because sassOptions.function cann't be shared cross workers, see https://github.com/umijs/mako/blob/master/e2e/fixtures.umi/config.sassLoader/.umirc.ts#L7
> fix: disable parallel sassLoader

- packages/mako/src/index.ts
- packages/mako/src/plugins/less/index.ts
- packages/mako/src/plugins/postcss/index.ts
- packages/mako/src/plugins/sass/index.ts
See: https://github.com/umijs/mako/blob/5f68c35a00688b7ca466948c0ad7a9a39e0acf6e/packages/mako/src/index.ts#L230,
"this" (the class instance) is lost.
> fix: less,sass,postcss loader panic

- crates/bundler-core/src/library/chunking_context.rs
- crates/bundler-core/src/library/contexts.rs
- crates/bundler-core/src/library/ecmascript/chunk.rs
- crates/bundler-core/src/library/ecmascript/content.rs
After update next.js to 15.3.0, sourcemaps is broken. We need to follow changes of: https://github.com/vercel/next.js/pull/77735
Close: https://github.com/umijs/mako/issues/1851
> fix(bundler): fix sourcemap

- Cargo.lock
- crates/cli/Cargo.toml
- crates/cli/src/constants.rs
- crates/cli/src/main.rs
- crates/cli/src/service/binary.rs
- crates/cli/src/service/install.rs
- crates/cli/src/service/mod.rs
- crates/cli/src/service/script.rs
1. 🌏 load `binary-mirror-config` to modify the binary configuration in npm pkg.
2. 🔧 add `service/binary.rs`, inject the mirror env variables.
3. 🐞 fix $cwd/node_modules/.bin not found
> feat: binary mirror config

- vendor/scripts/npm-utoo.sh
~~* 🔄 migrate to `utoo-release`, only handle `utoo-v*` tag~~
* 🛠 fix `ut` link not work
> fix: ut link not work

- Cargo.lock
- crates/cli/Cargo.toml
- crates/cli/src/helper/lock.rs
> Implement savePrefix Logic with ^ Default
* 🔭 Automatically adds ^ prefix when saving dependencies **only if**:
* No custom spec is provided (e.g., utoo install package@1.2.3 won't be modified)
* The version isn't already prefixed (e.g., ~1.2.3, ^1.2.3 remain unchanged)
> fix: save prefix

- Cargo.lock
- crates/cli/Cargo.toml
- crates/cli/src/cmd/run.rs
- crates/cli/src/helper/lock.rs
- crates/cli/src/helper/workspace.rs
- crates/cli/src/main.rs
🔹 **Basic `--workspace` Parameter**  
Supports targeting **a single workspace** by name or path:  
```bash
utoo run build --workspace=core       # by name
utoo run test --workspace=packages/ui # by exact path
```
🚧 **Single-workspace only**  
- Does _not_ yet support:  
- Glob patterns (`packages/*`)  
- Multiple workspaces (comma-separated)
> feat: run in workspace

- Cargo.lock
- crates/bundler-api/Cargo.toml
- crates/bundler-cli/Cargo.toml
- crates/bundler-core/Cargo.toml
- crates/bundler-napi/Cargo.toml
I use [`cargo-shear`](https://github.com/Boshen/cargo-shear) to detect and remove some useless rust dependencies, and `cargo build` execute is successfully at my local.
> chore: remove useless rust dependencies

- Cargo.lock
- crates/cli/Cargo.toml
- crates/cli/src/helper/lock.rs
- crates/cli/src/service/install.rs
- crates/cli/src/util/cloner.rs
- crates/cli/src/util/logger.rs
- crates/cli/src/util/node.rs
* 🪄 log improvements: `WARNING` => `WARN`.
* 🗜️ manual color output reset.
* 🐞 fixed nested node_modules path resolution during directory cleanup.
* 🔗 statically link openssl dependencies
> feat: log clean

- crates/bundler-core/src/library/chunking_context.rs
- crates/bundler-core/src/library/contexts.rs
- examples/with-less/project_options.json
A follow up pr for https://github.com/umijs/mako/issues/1902
In the last pr, just fix the app project output asset filename extension, this pr will solve the library project build.
> fix: library project output assets should generate corret extension

- Cargo.lock
- crates/bundler-api/src/project.rs
- crates/bundler-cli/src/main.rs
- crates/bundler-core/src/client/context.rs
- crates/bundler-core/src/config.rs
- crates/bundler-core/src/shared/mod.rs
- crates/bundler-core/src/shared/resolve/after_resolve_external_plugin.rs
- crates/bundler-core/src/shared/resolve/externals_plugin.rs
- crates/bundler-core/src/shared/resolve/mod.rs
- crates/bundler-napi/Cargo.toml
- examples/externals/.gitignore
- examples/externals/genHtml.js
- examples/externals/index.js
- examples/externals/package.json
- examples/externals/project_options.json
Pre: https://github.com/umijs/next.js/pull/3
Support externals config for utoo bundler.
User config as follows:
```json
{
"rootPath": "../../",
"projectPath": "./",
"config": {
"cleanDistDir": true,
"entry": [
{
"import": "./index.js"       
}
],
"output": {
"path": "./dist",
"filename": "[name].[contenthash:6].js",
"chunkFilename": "[name].[contenthash:8].js"
},
"optimization": {
"moduleIds": "named",
"minify": false
},
"externals": {
"foo": "foo",
"foo_require": "commonjs foo",
"foo_require2": {
"root": "foo",
"type": "commonjs"
},
"foo_import": "esm foo",
"foo_import2": {
"root": "foo",
"type": "esm"
}
}
}
}
```
The packge `external-package` will not be bundled here.
> feat: support externals

- Cargo.lock
- crates/bundler-core/src/config.rs
- crates/bundler-core/src/shared/resolve/externals_plugin.rs
- examples/externals/genHtml.js
- examples/externals/index.js
- examples/externals/project_options.json
- packages/bundler/src/types.ts
Pre PR: https://github.com/umijs/next.js/pull/13
Externals support script type, the config usage are as follows:
```json
{
"config": {
"externals": {
"foo_script": "script bar_script2@https://example.com/lib/script.js",
"foo_script2": {
"root": "bar_script2",
"type": "script",
"script": "https://example.com/lib/script2.js"
}
}
}
}
```
The user source code:
```ts
import foo_script from "foo_script";
import foo_script2 from "foo_script2";
console.log(foo_script, foo_script2);
```
External package `foo_script` and `foo_script2`will try to load from the script.
Output assets as follows:
> feat: externals support script

- crates/cli/src/cmd/deps.rs
- crates/cli/src/helper/lock.rs
> closes #1948 
* 🔨 Updated `is_pkg_outdated` logic to detect dependency changes in sub packages
* ✅  Added validation when creating a new workspace
* 🔒 Restricted engines validation to the main package only
> fix: sub package missing check

- examples/with-library/project_options.json
- examples/with-library/src/index.ts
- packages/pack/src/index.ts
- packages/pack/src/util.ts
A simple update:
- Adjust `createEnv` function to accept `options.defineEnv` by default
- Add externals config for umd  library bundler.
> fix: update createEnv & add externals for library examples

- crates/cli/src/helper/workspace.rs
fix #1948 
* 🚗 Improved root path detection logic
* 🐞 Returns current working directory (cwd) if package.json exists in cwd when cwd is not within a parent project’s sub-package
> fix: workspace root path

- crates/cli/src/helper/lock.rs
> fix #1966 
* 🔧 fix missing `version` and `bin` fields in workspace sub-packages
> fix: workspace bin

- crates/pack-api/src/app.rs
- crates/pack-api/src/entrypoint.rs
- crates/pack-api/src/library.rs
- examples/with-library/project_options.json
- 支持 `entry.import` 传入绝对路径:
修复思路: 把 `import` 在内部都统一处理成相对路径，绝对路径也转换成相对路径
后续还需要添加一个报错机制，用于 entry 的 resolve error。
ref issue: https://github.com/umijs/mako/issues/1972
> feat(pack): entry.import support absolute path

- crates/pack-api/src/app.rs
- crates/pack-api/src/library.rs
- crates/pack-core/src/library/runtime/runtime_code.rs
> perf(pack): remove useless runtime code for umd library output

- crates/cli/src/helper/lock.rs
* 🐞 Fixed the issue where workspace sub-packages with empty dependency fields `{}` failed validation.
* 🛠️ Fixed the issue where `dependencies` were missing during rendering in workspace sub-packages.
* 🔄 Fixed bug-version scenarios; when dependency validation fails, check version again.
> fix(pm): pkg lock outdated check

- crates/pack-api/src/app.rs
- crates/pack-api/src/library.rs
- crates/pack-api/src/project.rs
- package-lock.json
- packages/pack/package.json
MR 修复两个问题:
- utoo-pack 在非 monorepo 项目下的 entry resolver 问题
https://github.com/umijs/mako/blob/next/crates/pack-api/src/library.rs#L192
入口解析会用相对路径，当 `project_dir` 和  `root_dir` 在一个层级的时候(非 monorepo 单项目场景)，内部计算 `project_path` 和 `root_path` 会处理成 `""`，这种情况下，`relative_import` 实际上会处理成绝对路径，turbopack 会解析不到绝对路径，这里添加上一个分支处理，当存在 project_path 为 `""` 的情况下，用 `cwd` 计算相对路径。
- utoo-pack build cjs 依赖缺失的问题
> fix(pack): deal relative path under polyrepo project

- Cargo.lock
- Cargo.toml
- crates/pack-api/src/app.rs
- crates/pack-api/src/library.rs
- crates/pack-core/src/config.rs
- crates/pack-core/src/library/chunking_context.rs
- crates/pack-core/src/library/runtime/runtime_code.rs
- crates/pack-core/src/shared/resolve/externals_plugin.rs
- crates/pack-schema/src/lib.rs
- examples/externals/index.js
- examples/externals/project_options.json
- examples/with-library/project_options.json
- examples/with-library/src/index.ts
- packages/pack/config_schema.json
closes: #2010 
Before this pr megred, https://github.com/umijs/next.js/pull/30 should be merged.
support externals config like for the umd output format:
```json
{
"externals": {
"react": {
"root": "React",
"commonjs": "react"
}
}
}
```
> feat: externals support umd format

- .gitmodules
- crates/pack-api/src/app.rs
- crates/pack-api/src/library.rs
- crates/pack-api/src/project.rs
- crates/pack-core/src/import_map.rs
- crates/pack-core/src/util.rs
closes: #2020 
把之前处理 `entry.import` 在非 monorepo 项目下的绝对路径处理逻辑抽了个 `pack_core` 里面的util 方法，后续还有类似 issue 直接参考使用这个方法处理就好
> fix(pack): config.alias not work for absolute path

- .github/workflows/pack-release.yml
镜像 `nodejs-rust:lts-alpine` 里面应该已经有 llvm-dev 这个依赖了，~~可以不用安装，会出现依赖覆盖导致抛错的问题~~
用最新的 `llvm-dev` 依赖，参考 swc 的处理: https://github.com/swc-project/swc/blob/main/.github/workflows/publish-npm-package.yml#L122
> fix: docker nodejs-rust:lts-alpine contains llvm-dev

- examples/with-style-loader/project_options.json
- packages/pack/src/types.ts
`inlineCss` 的两个参数 `insert` 以及 `insertType` 可以不传，默认情况下 insertType 会处理成 `header`.
> fix(pack): inlineCss config type could be optional

- Cargo.lock
- crates/pack-api/Cargo.toml
- crates/pack-api/src/entrypoint.rs
- crates/pack-api/src/project.rs
- crates/pack-core/src/config.rs
- crates/pack-core/src/emit.rs
- crates/pack-schema/src/lib.rs
- crates/pack-tests/tests/snapshot/basic/copy/config.json
- crates/pack-tests/tests/snapshot/basic/copy/input/index.js
- crates/pack-tests/tests/snapshot/basic/copy/input/reset.css
- crates/pack-tests/tests/snapshot/basic/copy/output/crates_pack-tests_tests_snapshot_basic_copy_input_index_3611f3a0.js
- crates/pack-tests/tests/snapshot/basic/copy/output/crates_pack-tests_tests_snapshot_basic_copy_input_index_3611f3a0.js.map
- crates/pack-tests/tests/snapshot/basic/copy/output/main.js
- crates/pack-tests/tests/snapshot/basic/copy/output/main.js.map
- crates/pack-tests/tests/snapshot/basic/copy/output/reset.css
- examples/define/.gitignore
- examples/react/.gitignore
- examples/react/README.md
- examples/react/package.json
- examples/react/project_options.json
- examples/react/src/App.tsx
- examples/react/src/foo.ts
- examples/react/src/index.tsx
- examples/react/static/index.css
- packages/pack/config_schema.json
- packages/pack/src/binding.d.ts
- packages/pack/src/types.ts
closes: #2006 
支持 `output.copy` 配置用于承接 https://webpack.js.org/plugins/copy-webpack-plugin/ 的能力，配置设计如下:
```json
"output": {
"copy": [
{
"from": "input/reset.css",
"to": "./reset.css"
}
]
}
```
目前还没支持 glob 匹配，后续需要完善一下。
参考 `pack-tests` 中的测试 case。
> feat(pack): support config.copy

- crates/pack-core/src/client/context.rs
- crates/pack-core/src/config.rs
- crates/pack-core/src/library/contexts.rs
Ignore configuration in development mode to not break HMR
Snapshot need to support dev mode in future.
> fix(pack): ignore config concatenate_modules in dev mode

- crates/pack-core/src/library/chunking_context.rs
- crates/pack-tests/tests/snapshot/umd/async-module/config.json
- crates/pack-tests/tests/snapshot/umd/async-module/input/a.js
- crates/pack-tests/tests/snapshot/umd/async-module/input/b.js
- crates/pack-tests/tests/snapshot/umd/async-module/input/index.js
- crates/pack-tests/tests/snapshot/umd/async-module/input/main.js
- crates/pack-tests/tests/snapshot/umd/async-module/input/shared.js
- crates/pack-tests/tests/snapshot/umd/async-module/output/main.js
- crates/pack-tests/tests/snapshot/umd/async-module/output/main.js.map
- examples/react/.gitignore
closes: #2132 
使用 ManifestLoaderChunkItem 去处理 umd bundle 里面的 async chunk，类似于 webpack 的 output.asyncChunks 设置为 false，在 umd 的时候默认用 ManifestLoaderChunkItem.
更新了快照测试
> fix(pack): umd support bundle async chunk

- crates/pack-core/src/shared/transforms/modularize_imports.rs
- crates/pack-schema/src/lib.rs
- examples/react/src/App.tsx
- examples/react/src/index.tsx
- packages/pack/config_schema.json
- packages/pack/src/webpackCompat.ts
part of: https://github.com/utooland/utoo/issues/2165
把 default import 和 namespace import 的开关开放先，后续还需要添加一个 style 的配置(需要先把 swc 升级上来)，用于处理样式文件的导入。
等 `style` 添加了构造一组快照测试出来。
> feat(pack): modularizeImport plugin support handleDefaultImport & handleNamespaceImport config

- .cargo/config.toml
https://github.com/utooland/utoo/actions/runs/17570673815/job/49906133440
> fix(ci): x86_64 pc windows msvc should enable tokio unstable

- crates/pack-core/src/import_map.rs
alias 一下:
- `react`
- `react-dom`
- `react/`
- `react-dom/`
> feat(pack): enable react / react-dom alias by default

- crates/pack-core/js/src/react-refresh/internal/helpers.ts
- crates/pack-core/src/client/react_refresh.rs
- crates/pack-core/src/embed_js.rs
- crates/pack-core/src/import_map.rs
closes: #2204 
https://github.com/user-attachments/assets/dff2c929-4dc1-4ed4-bca4-b75b12bf74e4
主要是两个问题修复:
- 修复 react-refresh 的 runtime code 没有正确注入，导致 hmr 走不到 react-refresh 上的 runtime 逻辑来
- 修复 react-refresh runtime code 中找不到 `module` 导致 jsx 更新降级
> fix(pack): hmr not work for react app
